### ISSUE TITLE
使用ingress域名后，为什么springboot连接失败

### ISSUE THREAD

**Issue by zhangwei900808** [dujincan/helm-rabbitmq#1]
我的微服务使用的是ingress配置域名方式，但是连接失败，这个咋解决啊？

application.yml
```
spring:
  rabbitmq:
    host: rabbitmq.testapi.seaurl.com
    port: 5672
    username: 
    password: 
```

values.yaml
```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod-http01
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
  hostName: rabbitmq.testapi.seaurl.com
  tls: true
  tlsSecret: rabbitmq-tls
persistence:
  storageClass: "alicloud-disk-ssd"
  size: 20Gi

```
